name: LESSs
description: Book your peace of mind with Less

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  app_review: ^2.1.1+1
  #Replace this as non-null not supported
  #barcode_scan: ^4.2.0
  another_flushbar: ^1.10.28
  carousel_slider: ^4.0.0
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.8
  eventify: ^1.0.0
  email_validator: ^2.0.1
  enum_to_string: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_local_notifications: ^9.3.2
  flutter_native_timezone: ^2.0.0
  firebase_remote_config: ^2.0.0
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  firebase_auth: ^3.3.7
  firebase_dynamic_links: ^4.0.6
  firebase_storage: ^10.2.7
  flutter_datetime_picker: ^1.5.1
  geolocator: ^8.2.0
  geoflutterfire: ^3.0.3
  google_sign_in: ^5.2.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  map_launcher: ^2.2.1+1
  pinput: ^1.2.2
  path_provider: ^2.0.9
  #Replace this as non-null not supported
  #progress_dialog: ^1.2.4
  package_info: ^2.0.2
  pie_chart: ^5.1.0
  shared_preferences: ^2.0.13
  qr_flutter: ^4.0.0
  share: ^2.0.4
  http: ^0.13.4
  image_picker: ^0.8.4+9
  #upi_pay: ^1.0.1
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  video_player: ^2.2.18
  version: ^2.0.0
  #Replace this as non-null not supported
  #weekday_selector_formfield: ^1.0.4
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #- logo_icon.png
    - sukoon_subheading.png
    - background.png
    - ticket.jpg
    - 1.jpg
    - 2.jpg
    - 3.jpg
    - 4.jpg
    - 5.jpg
    - 6.jpg
    - whatsapp.png
    - cancelled.png
    - cancelled_2.png
    - qrcode.png
    - faq.png
    - sharing.png
    - sales.jpg
    - notFound.png
    - regain.jpg
    - salon.png
    - placeOfWorship.png
    - restaurant.png
    - sportsCenter.png
    - gym.png
    - user_account.png
    - notFound1.png
    - notFound2.png
    - noFavourites.png
    - infoCustomer.png
    - infoBusiness.png
    - less_name.png
    - offers_icon.png
    - how_to_book_slot.png
    - how_to_register_business.png
    # - screen_login2.png
    # - screen_homepage.png
    # - screen_search.png
    # - screen_view_list.png
    # - screen_view_slots.png
    # - screen_token.png
    # - bscreen_register.png
    # - bscreen_place_list.png
    # - bscreen_add_new_place.png
    # - bscreen_fill_details_general.png
    # - bscreen_fill_details_offer.png
    # - bscreen_fill_details_save.png
    - search_home.png
    - well_done.png
    - calling_codes.json
    - bigpiq_gpay.jpg
    - ourStory.png
    - employee.png
    - tokens.png
    - forms.png
    - settings.png
    - applications.png
    - places.png
    - privacy.png
    - terms.png
    - contactus.png
    - donate.png
    - bigpiq_upi.jpg
    - rupee_icon.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AkkuratPro
      fonts:
        - asset: fonts/AkkRg_Pro_1.otf
    - family: AkkuratThin
      fonts:
        - asset: fonts/AkkLg_Pro_Thin_1.otf
    - family: RalewayRegular
      fonts:
        - asset: fonts/Raleway-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
