name: LESSs
description: Book your peace of mind with Less

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  map_launcher: ^0.4.4
  #Added http for accessing APIs for data
  
  pinput: ^0.2.3
  path_provider: ^2.0.2
  shared_preferences: ^0.5.7
  flutter_datetime_picker: ^1.5.1
  weekday_selector_formfield: ^1.0.4   
  json_annotation: ^3.1.0 
  intl: ^0.17.0
  progress_dialog: ^1.2.4
  url_launcher: ^6.0.0-nullsafety.6
  geolocator: 7.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0 
  cloud_firestore: 1.0.6
  geoflutterfire: 3.0.0-nullsafety.2
  google_sign_in: ^4.5.5
  firebase_core: ^1.1.0
  firebase_crashlytics: 2.0.1
  firebase_auth: ^1.1.2
  firebase_dynamic_links: 2.0.1
  firebase_storage: ^8.0.4
  uuid: ^2.2.2
 #Added for QR code scan and generate
  barcode_scan_fix: ^1.0.2
  qr_flutter: ^3.2.0
  share: ^0.6.5+4 
  #Flushbar
  another_flushbar: ^1.10.20
  #forcarousel
  carousel_slider: ^2.3.1  
  eventify: ^0.1.4
  package_info: ^2.0.0
  flutter_local_notifications: 5.0.0+1
  #flutter_local_notifications: ^6.0.0
  flutter_native_timezone: ^1.0.4
  app_review: 2.1.1+1
  auto_size_text: ^2.1.0
  video_player: ^1.0.1
  http: 0.13.1
  enum_to_string: ^2.0.1
  flutter_staggered_grid_view: ^0.3.2
  image_picker: ^0.7.4
  firebase_messaging: 9.1.2
  email_validator: ^1.0.6
  charts_flutter: ^0.10.0
  pie_chart: ^4.0.1
  firebase_remote_config: 0.10.0-dev.1
  upi_pay: ^0.2.4
  version: ^2.0.0
  youtube_player_flutter: 7.0.0+7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:    
    #- logo_icon.png
    - sukoon_subheading.png
    - background.png   
    - ticket.jpg
    - 1.jpg
    - 2.jpg
    - 3.jpg
    - 4.jpg
    - 5.jpg
    - 6.jpg    
    - whatsapp.png    
    - cancelled.png
    - cancelled_2.png
    - qrcode.png
    - faq.png
    - sharing.png
    - sales.jpg
    - notFound.png
    - regain.jpg  
    - salon.png    
    - placeOfWorship.png
    - restaurant.png
    - sportsCenter.png
    - gym.png
    - user_account.png
    - notFound1.png
    - notFound2.png
    - noFavourites.png
    - infoCustomer.png 
    - infoBusiness.png  
    - less_name.png
    - offers_icon.png    
    - how_to_book_slot.png
    - how_to_register_business.png
   # - screen_login2.png    
   # - screen_homepage.png
   # - screen_search.png
   # - screen_view_list.png
   # - screen_view_slots.png
   # - screen_token.png
    # - bscreen_register.png
    # - bscreen_place_list.png
    # - bscreen_add_new_place.png
    # - bscreen_fill_details_general.png
    # - bscreen_fill_details_offer.png
    # - bscreen_fill_details_save.png
    - search_home.png
    - well_done.png
    - calling_codes.json
    - bigpiq_gpay.jpg 
    - ourStory.png
    - employee.png
    - tokens.png
    - forms.png
    - settings.png
    - applications.png
    - places.png
    - privacy.png
    - terms.png
    - contactus.png
    - donate.png
    - bigpiq_upi.jpg
    - rupee_icon.png
    
  
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: AkkuratPro
        fonts:
          - asset: fonts/AkkRg_Pro_1.otf
      - family: AkkuratThin
        fonts:
          - asset: fonts/AkkLg_Pro_Thin_1.otf
      - family: RalewayRegular
        fonts:
          - asset: fonts/Raleway-Regular.ttf      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
