enum EntityType {
  PLACE_TYPE_VACCINATION_CENTER,

  PLACE_TYPE_SUPERMARKET,
  PLACE_TYPE_APARTMENT,
  PLACE_TYPE_HOSPITAL,
  PLACE_TYPE_MEDICAL_CLINIC,
  PLACE_TYPE_PHARMACY,
  PLACE_TYPE_SHOP,
  PLACE_TYPE_WORSHIP,
  PLACE_TYPE_RESTAURANT,
  PLACE_TYPE_SALON,
  PLACE_TYPE_SCHOOL,
  PLACE_TYPE_PUBLIC_OFFICE,
  PLACE_TYPE_PRIVATE_OFFICE,
  PLACE_TYPE_GYM,
  PLACE_TYPE_SPORTS,
  PLACE_TYPE_POPSHOP,
  PLACE_TYPE_DIAGNOSTICS,

  PLACE_TYPE_MALL,
  PLACE_TYPE_BANK,
  PLACE_TYPE_REALSTATE,
  PLACE_TYPE_CAR_SERVICE,
  PLACE_TYPE_BIKE_SERVICE,
  PLACE_TYPE_PHONE_SERVICE,
  PLACE_TYPE_LAPTOP_SERVICE,

  PLACE_TYPE_OTHERS
}
